pub mod day1;
pub mod day2;
pub mod day3;
pub mod day4;
pub mod day5;
pub mod day6;
pub mod day7;
pub mod day8;
pub mod day9;
pub mod day10;
pub mod day11;
pub mod parsing;
pub mod compare;
mod day1_tests;
mod day2_tests;
mod day3_tests;
mod day4_tests;
mod day5_tests;
mod day6_tests;
mod day7_tests;
mod day8_tests;
mod day9_tests;
mod day10_tests;
mod day11_tests;
mod compare_tests;